app:
  jokesUrl: https://official-joke-api.appspot.com
  schedule: "*/20 * * * * *"
  redisSeconds: 60
  mail:
    fromName: "Jokes retriever App"
    fromAddress: noreply@jokesapp.com
    toAddress: demo1@example.com,demo2@example.com
    bccAddress: demo3@example.com
    subject: "New Joke received!!!"
  ftp:
    serverName: 127.0.0.1
    port: 2121
    userName: demo
    password: demo

spring:
  application:
    name: Demo
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration/postgres
    sql-migration-prefix: V
    table: demo_schema_version
    schemas: demo
    init-sqls: CREATE SCHEMA IF NOT EXISTS demo;
    user: demo
    password: demo
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5444/demo
    userName: demo
    password: demo
  jpa:
    hibernate.ddl-auto: none
    show-sql: false
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      default_schema: demo
  mail:
    host: localhost
    port: 1025
    default-encoding: UTF-8
    protocol: smtp
  redis:
    host: localhost
    port: 16379
  rabbitmq:
    username: demo
    password: demo
    host: localhost
    port: 5672
    broker-url: tcp://127.0.0.1:5672
  cloud:
    stream:
      defaultBinder: rabbit
      bindings:
        PersonsOutputChannel:
          destination: persons-topic
          content-type: application/json
      rabbit:
        bindings:
          PersonsOutputChannel:
            producer:
              durable: false
              transacted: true
              routing-key-expression: headers.myRoutingKey
              exchangeType: topic
